### ISSUE TITLE
var storage = new LocalStorage(); giving me errors

### ISSUE THREAD

**Issue by tussutryllirinn** [hanssens/localstorage#22]
I'm trying to use your feature but keep getting this error when I'm debugging.

First time trying to use with no progress. Can you shed a light on this ?

I attached 2 pictures of my code.
![errorhans](https://user-images.githubusercontent.com/34026691/39778953-45f581a0-52f7-11e8-9422-2bf3e3d05b97.PNG)
![errorhans2](https://user-images.githubusercontent.com/34026691/39778954-4613e88e-52f7-11e8-958b-c434a06821ad.PNG)

**Comment by hanssens** [comment]
Duplicate issue of #19. Following it up in there.

**Comment by SreeluMandiga** [comment]
What is the solution?. I have the same issue.
