### ISSUE TITLE
Is it working across web appllications

### ISSUE THREAD

**Issue by acrigney** [hanssens/localstorage#24]
Sorry I could not get the local storage data to be read from another ASP.NET MVC web app.
I guess I can debug into your code or use fiddler.

**Comment by acrigney** [comment]
Mate its very hard to do that as I am using tihs NakedObjects framework.
But I read that local storage does not work across domains AT ALL???

**Comment by hanssens** [comment]
Sure, it does. If you have the `.localstorage` file it can be transferred and/or re-used between different .NET Core apps. However, to prevent any concurrency problems I wouldn't recommend to use it as a database storage between different apps.

**Comment by acrigney** [comment]
Awesome but I am working with .net 4,5,2 and4,6,1?
Its just for the user winows Prinicipal, no password is stored.

**Comment by hanssens** [comment]
Hope in the meantime you've tried it, @acrigney. But the lib targets netstandard2.0 which means it should be compatible with .NET 4.6.1 and higher. 

If you have issues with it, let me know.
