### ISSUE TITLE
Handling file´s changes

### ISSUE THREAD

**Issue by darianbenito** [hanssens/localstorage#32]
We can watch the file´s changes at runtime and reload the configuration like [nJupiter.Configuration](https://github.com/njupiter/njupiter) (deprecated project). With that, you don´t need to restart the application if any configuration changed or a new configuration was added. 
We can use FileSystemWatcher (System.IO).

**Comment by hanssens** [comment]
Thanks for the suggestion, @darianbenito. But I personally haven't found a need for an auto-refresh or auto-reload mechanism yet. Can you explain a case where this would be helpful?

Instead, my first thoughts are that it would make sense that the consuming application would implement a FileSystemWatcher on itself and refresh the localstorage accordingly.
