### ISSUE TITLE
Localstorage on many servers instances

### ISSUE THREAD

**Issue by gabrielfava** [hanssens/localstorage#34]
Hello, first, congratulations for this module, awesome!

I would like to know how its work for an app with multiple instances, like on AWS with a load balancer and Auto scaling system...
It will preserve the localstorage for all instances, example, if a save some users information on localstorage, its will be shared between others instances OR the instances have your own localstorage ?

**Comment by hanssens** [comment]
Stating the obvious, but please be aware that the lib is not built for multi-concurrency or distributed scenarios. It just isn't supposed to go there. That being said, I would say that keep LocalStorage per instance of your AWS container is fine.  

For what it's worth, in the latest [v2.1.0 release](https://github.com/hanssens/localstorage/releases/tag/v2.1.0) I've started working on the 'read-only' mode. This is still a work in progress, but theoretically you can refer to the same localstorage file as much as you want. I can't stress enough that this is very much a work in progress, though. ;) 

Hope that helped a bit.
