### ISSUE TITLE
Remove LocalStorage with key

### ISSUE THREAD

**Issue by mhmsignin** [hanssens/localstorage#36]
first thank you really, i need this until extera security option
second  how to remove local storage with key? it's possible?
like : storage.Remove("somKey");

**Comment by hanssens** [comment]
Thanks @mhmsignin. You're right, I've just published [v2.1.0](https://github.com/hanssens/localstorage/releases/tag/v2.1.0) where the `.Remove()` operation is now available. 
See [this example](https://github.com/hanssens/localstorage/blob/master/LocalStorage.Tests/LocalStorageTests.cs#L255-L256) in the tests as well.
