### ISSUE TITLE
Can we use this for sessionStorage too?

### ISSUE THREAD

**Issue by eugeniosegura** [hanssens/localstorage#44]
Can we use this for sessionStorage too?

**Comment by hanssens** [comment]
No, [Window.session](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is a browser thing and not related to this library at all.
 
Please see the ["What is it not" in the README](https://github.com/hanssens/localstorage#what-is-it-not) for more details. Hope that makes it clear.
